<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="4770" started-at="2018-11-08T19:27:55Z" finished-at="2018-11-08T19:28:00Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="4770" started-at="2018-11-08T19:27:55Z" finished-at="2018-11-08T19:28:00Z">
      <class name="ZyTest.CustomerOnboardingApp.FirstTest">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:ZyTest.CustomerOnboardingApp.FirstTest@6bdf28bb]" name="beforeTest" is-config="true" duration-ms="9" started-at="2018-11-09T00:57:55Z" finished-at="2018-11-09T00:57:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="testCreateCustomer()[pri:0, instance:ZyTest.CustomerOnboardingApp.FirstTest@6bdf28bb]" name="testCreateCustomer" duration-ms="3082" started-at="2018-11-09T00:57:55Z" finished-at="2018-11-09T00:57:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateCustomer -->
        <test-method status="FAIL" signature="testGetTenantConfig()[pri:0, instance:ZyTest.CustomerOnboardingApp.FirstTest@6bdf28bb]" name="testGetTenantConfig" duration-ms="830" started-at="2018-11-09T00:57:58Z" finished-at="2018-11-09T00:57:59Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [201] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [201] but found [404]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:372)
	at org.testng.Assert.assertEquals(Assert.java:382)
	at ZyTest.CustomerOnboardingApp.FirstTest.testGetTenantConfig(FirstTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetTenantConfig -->
        <test-method status="PASS" signature="testUploadXlsPositivecase()[pri:0, instance:ZyTest.CustomerOnboardingApp.FirstTest@6bdf28bb]" name="testUploadXlsPositivecase" duration-ms="829" started-at="2018-11-09T00:57:59Z" finished-at="2018-11-09T00:58:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUploadXlsPositivecase -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:ZyTest.CustomerOnboardingApp.FirstTest@6bdf28bb]" name="afterTest" is-config="true" duration-ms="0" started-at="2018-11-09T00:58:00Z" finished-at="2018-11-09T00:58:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- ZyTest.CustomerOnboardingApp.FirstTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
